# Site settings
title: Circle Zhou
description: Musings in CS, sports, and music.

url: http://CircleZ3791117.github.io

about_title: 吾
projects_title: 集

# User settings
user_description_appendix: |
  This site is built in [Jekyll][jekyll] and hosted on [Github Pages][gh-pages]. If you like it, please star it on
  [Github][github].

  [github]: https://github.com/CircleZ3791117/CircleZ3791117.github.io
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com


email: CircleZ3791117@gmail.com
linkedin: CircleZ3791117
github: CircleZ3791117
angellist: CircleZ3791117

relevant_tags: ['匠心独运集', '温故知新集', '韦编三绝集', '朝花夕拾集']

resume_url: 

author: Circle Zhou
author_title: 采菊东篱下，悠然现南山
author_photo: profile-photo.png
user_description_short: |
  嗨，我是周环（circlezhou），一个喜欢编程和古文的理科生/开发者。

  现居天府之国——成都。正在修行，路漫漫其修远兮，吾将上下而求索。

## Disqus
disqus_identifier: circlez3791117

## Tracker
google_analytics_id: UA-109461282-1

keywords: 'software,engineer,design,python,music'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']