# Site settings
title: Circle Zhou
description: Musings in CS, sports, and music.

url: http://circlez3791117.com

about_title: Contact
projects_title: Musings

# User settings
user_description_appendix: |
  This site is built in [Jekyll][jekyll] and hosted on [Github Pages][gh-pages]. If you like it, feel free to fork it on
  [Github][github].

  [github]: https://github.com/CircleZ3791117/CircleZ3791117.github.io
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com


email: CircleZ3791117@gmail.com
linkedin: CircleZ3791117
github: CircleZ3791117
angellist: CircleZ3791117

relevant_tags: ['tech', 'design', 'music']

resume_url: https://drive.google.com/open?id=0B5vVg0C4jFacXzJ4b09XZmw2amc

author: CircleZ3791117
author_title: Software Developer
author_photo: profile-photo.jpg
user_description_short: |
  My name is Circle Zhou. I'm a software engineer based in Chendu. My preferred language is
  [Python][python].

  Away from the keyboard, I make food and music.

  [python]: https://www.python.org/


## Disqus
disqus_identifier: CircleZ3791117

## Tracker
google_analytics_id: UA-109461282-1

keywords: 'software,engineer,design,python,music'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']